In [ ]:
import os
import numpy as np
import pandas as pd

In [2]:
mimic_iv_patients = 'local-path-where-mimic-located/physionet.org/files/mimic-iv-1.0/core/patients.csv'
mimic_iv_admissions = 'local-path-where-mimic-located/physionet.org/files/mimic-iv-1.0/core/admissions.csv'
mimic_iv_icu_stays = 'local-path-where-mimic-located/physionet.org/files/mimic-iv-1.0/icu/icustays.csv'

mimic_cxr_meta = 'local-path-where-mimic-located/physionet.org/files/mimic-cxr-jpg/2.0.0/mimic-cxr-2.0.0-metadata.csv'

patient_images = pd.read_csv(mimic_cxr_meta)

In [3]:
#list(patient_images)
patient_da = pd.read_csv(mimic_iv_patients)
patient_da

        subject_id gender  anchor_age  anchor_year anchor_year_group  dod
0         10000048      F          23         2126       2008 - 2010  NaN
1         10002723      F           0         2128       2017 - 2019  NaN
2         10003939      M           0         2184       2008 - 2010  NaN
3         10004222      M           0         2161       2014 - 2016  NaN
4         10005325      F           0         2154       2011 - 2013  NaN
...            ...    ...         ...          ...               ...  ...
382273    19998203      M          29         2132       2011 - 2013  NaN
382274    19998350      M          52         2127       2011 - 2013  NaN
382275    19999068      M          63         2161       2011 - 2013  NaN
382276    19999270      M          33         2184       2014 - 2016  NaN
382277    19999298      M          20         2177       2011 - 2013  NaN

[382278 rows x 6 columns]

In [4]:
cxr_dataset = patient_images

In [5]:
cols = ['dicom_id', 'subject_id', 'study_id', 'StudyDate', 'ViewPosition', 'PatientOrientationCodeSequence_CodeMeaning']
cxr_dataset = patient_images[cols]
cxr_dataset = cxr_dataset.rename(columns={"ViewPosition": "cxr_view"})

In [6]:
cxr_dataset = cxr_dataset.rename(columns={"PatientOrientationCodeSequence_CodeMeaning": "cxr_orientation"})

In [7]:
cxr_dataset

,dicom_id,subject_id,study_id,StudyDate,cxr_view,cxr_orientation
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,21800506,PA,Erect
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,21800506,LATERAL,Erect
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,21800626,PA,Erect
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,21800626,LATERAL,Erect
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,21800723,AP,NaN
...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,21520708,PA,Erect
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,21520708,LATERAL,Erect
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,21451104,AP,Erect
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,21451102,AP,Erect
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,21451103,AP,Recumbent

In [9]:
patient_data = pd.read_csv(mimic_iv_patients)

In [10]:
final_dataset = cxr_dataset.merge(patient_data[['subject_id', 'gender']], on='subject_id', how='left')
final_dataset

,dicom_id,subject_id,study_id,StudyDate,cxr_view,cxr_orientation,gender
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,21800506,PA,Erect,F
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,21800506,LATERAL,Erect,F
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,21800626,PA,Erect,F
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,21800626,LATERAL,Erect,F
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,21800723,AP,NaN,F
...,...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,21520708,PA,Erect,F
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,21520708,LATERAL,Erect,F
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,21451104,AP,Erect,F
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,21451102,AP,Erect,F
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,21451103,AP,Recumbent,F

In [11]:
patients_adm = pd.read_csv(mimic_iv_admissions)
new_patients_adm = patients_adm.drop_duplicates(subset=['subject_id'], keep='last')

In [12]:
final_dataset_2 = final_dataset.merge(new_patients_adm[['subject_id', 'ethnicity', 'hadm_id']], on='subject_id', how='left')
final_dataset_2

,dicom_id,subject_id,study_id,StudyDate,cxr_view,cxr_orientation,gender,ethnicity,hadm_id
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,21800506,PA,Erect,F,WHITE,25742920.0
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,21800506,LATERAL,Erect,F,WHITE,25742920.0
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,21800626,PA,Erect,F,WHITE,25742920.0
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,21800626,LATERAL,Erect,F,WHITE,25742920.0
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,21800723,AP,NaN,F,WHITE,25742920.0
...,...,...,...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,21520708,PA,Erect,F,WHITE,27674281.0
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,21520708,LATERAL,Erect,F,WHITE,27674281.0
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,21451104,AP,Erect,F,UNKNOWN,23865745.0
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,21451102,AP,Erect,F,UNKNOWN,23865745.0
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,21451103,AP,Recumbent,F,UNKNOWN,23865745.0

In [13]:
final_dataset_2['study_date'] = final_dataset_2['StudyDate'].apply(lambda x: int(str(x)[:4]))
final_dataset_2

,dicom_id,subject_id,study_id,StudyDate,cxr_view,cxr_orientation,gender,ethnicity,hadm_id,study_date
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,21800506,PA,Erect,F,WHITE,25742920.0,2180
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,21800506,LATERAL,Erect,F,WHITE,25742920.0,2180
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,21800626,PA,Erect,F,WHITE,25742920.0,2180
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,21800626,LATERAL,Erect,F,WHITE,25742920.0,2180
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,21800723,AP,NaN,F,WHITE,25742920.0,2180
...,...,...,...,...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,21520708,PA,Erect,F,WHITE,27674281.0,2152
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,21520708,LATERAL,Erect,F,WHITE,27674281.0,2152
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,21451104,AP,Erect,F,UNKNOWN,23865745.0,2145
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,21451102,AP,Erect,F,UNKNOWN,23865745.0,2145
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,21451103,AP,Recumbent,F,UNKNOWN,23865745.0,2145

In [14]:
# mimic_iv_icu_stays
icu_stays_table = pd.read_csv(mimic_iv_icu_stays)
icu_stays_table

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,17867402,24528534,31793211,Trauma SICU (TSICU),Trauma SICU (TSICU),2154-03-03 04:11:00,2154-03-04 18:16:56,1.587454
1,14435996,28960964,31983544,Trauma SICU (TSICU),Trauma SICU (TSICU),2150-06-19 17:57:00,2150-06-22 18:33:54,3.025625
2,17609946,27385897,33183475,Trauma SICU (TSICU),Trauma SICU (TSICU),2138-02-05 18:54:00,2138-02-15 12:42:05,9.741725
3,18966770,23483021,34131444,Trauma SICU (TSICU),Trauma SICU (TSICU),2123-10-25 10:35:00,2123-10-25 18:59:47,0.350544
4,12776735,20817525,34547665,Neuro Stepdown,Neuro Stepdown,2200-07-12 00:33:00,2200-07-13 16:44:40,1.674769
...,...,...,...,...,...,...,...,...
76535,15368898,27299174,39990887,Trauma SICU (TSICU),Trauma SICU (TSICU),2126-06-13 01:00:00,2126-06-13 20:28:35,0.811516
76536,15721773,28911582,39991872,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2177-11-08 14:09:00,2177-11-10 00:24:54,1.427708
76537,12275003,22562812,39992247,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),2182-08-15 09:37:33,2182-08-16 17:25:44,1.325127
76538,17577670,24221219,39993265,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2154-01-03 22:50:26,2154-01-06 12:44:43,2.579363
76539,17840864,22695803,39999810,Neuro Intermediate,Neuro Intermediate,2115-12-01 00:37:00,2115-12-05 18:27:57,4.743715

In [15]:
final_dataset_2 = final_dataset_2.merge(patient_data[['subject_id', 'anchor_age', 'anchor_year']], on='subject_id', how='left')
final_dataset_2

,dicom_id,subject_id,study_id,StudyDate,cxr_view,cxr_orientation,gender,ethnicity,hadm_id,study_date,anchor_age,anchor_year
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,21800506,PA,Erect,F,WHITE,25742920.0,2180,52.0,2180.0
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,21800506,LATERAL,Erect,F,WHITE,25742920.0,2180,52.0,2180.0
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,21800626,PA,Erect,F,WHITE,25742920.0,2180,52.0,2180.0
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,21800626,LATERAL,Erect,F,WHITE,25742920.0,2180,52.0,2180.0
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,21800723,AP,NaN,F,WHITE,25742920.0,2180,52.0,2180.0
...,...,...,...,...,...,...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,21520708,PA,Erect,F,WHITE,27674281.0,2152,19.0,2152.0
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,21520708,LATERAL,Erect,F,WHITE,27674281.0,2152,19.0,2152.0
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,21451104,AP,Erect,F,UNKNOWN,23865745.0,2145,57.0,2145.0
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,21451102,AP,Erect,F,UNKNOWN,23865745.0,2145,57.0,2145.0
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,21451103,AP,Recumbent,F,UNKNOWN,23865745.0,2145,57.0,2145.0

In [16]:
birth_year = final_dataset_2['anchor_year'] - final_dataset_2['anchor_age']
age = final_dataset_2['study_date'] - birth_year

In [17]:
final_dataset_2['age'] = age

In [18]:
final_dataset_2

,dicom_id,subject_id,study_id,StudyDate,cxr_view,cxr_orientation,gender,ethnicity,hadm_id,study_date,anchor_age,anchor_year,age
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,21800506,PA,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,21800506,LATERAL,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,21800626,PA,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,21800626,LATERAL,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,21800723,AP,NaN,F,WHITE,25742920.0,2180,52.0,2180.0,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,21520708,PA,Erect,F,WHITE,27674281.0,2152,19.0,2152.0,19.0
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,21520708,LATERAL,Erect,F,WHITE,27674281.0,2152,19.0,2152.0,19.0
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,21451104,AP,Erect,F,UNKNOWN,23865745.0,2145,57.0,2145.0,57.0
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,21451102,AP,Erect,F,UNKNOWN,23865745.0,2145,57.0,2145.0,57.0
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,21451103,AP,Recumbent,F,UNKNOWN,23865745.0,2145,57.0,2145.0,57.0

In [133]:
final_dataset_2['stay_expire'] = 0
from tqdm import tqdm

In [134]:
# looping through users!
for index, row in tqdm(final_dataset_2.iterrows()):
    cxr_patient = row['subject_id']
    cxr_date = row['StudyDate']
    # check admission entries for patient
    cxr_admissions = patients_adm[patients_adm['subject_id'] == cxr_patient]
    for index2, row2 in cxr_admissions.iterrows():
        admittime = ''.join(row2['admittime'][:10].split('-'))
        dischtime = ''.join(row2['dischtime'][:10].split('-'))
        if cxr_date >= int(admittime) and cxr_date <= int(dischtime):
            #print(index, row['hospital_expire'])
            #print(index, row2['hospital_expire_flag'])
            final_dataset_2.at[index,'stay_expire'] = row2['hospital_expire_flag']

377110it [08:13, 764.92it/s]

In [135]:
final_dataset_2['stay_expire'].value_counts()

0    358621
1     18489
Name: stay_expire, dtype: int64

In [136]:
final_dataset_2['icu_stay_los'] = 0
final_dataset_2['icu_stay'] = 0

In [137]:
# looping through users!
for index, row in tqdm(final_dataset_2.iterrows()):
    cxr_patient = row['subject_id']
    cxr_date = row['StudyDate']
    # check admission entries for patient
    icu_admissions = icu_stays_table[icu_stays_table['subject_id'] == cxr_patient]
    for index2, row2 in icu_admissions.iterrows():
        intime = ''.join(row2['intime'][:10].split('-'))
        outtime = ''.join(row2['outtime'][:10].split('-'))
        if cxr_date >= int(intime) and cxr_date <= int(outtime):
            #print(index, row['hospital_expire'])
            #print(index, row2['hospital_expire_flag'])
            final_dataset_2.at[index,'icu_stay_los'] = row2['los']
            final_dataset_2.at[index,'icu_stay'] = 1

377110it [04:24, 1425.45it/s]

In [138]:
final_dataset_2

,dicom_id,subject_id,study_id,StudyDate,cxr_view,cxr_orientation,gender,ethnicity,hadm_id,study_date,anchor_age,anchor_year,age,stay_expire,icu_stay_los,icu_stay
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,21800506,PA,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0,0,0.000000,0
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,21800506,LATERAL,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0,0,0.000000,0
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,21800626,PA,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0,0,0.000000,0
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,21800626,LATERAL,Erect,F,WHITE,25742920.0,2180,52.0,2180.0,52.0,0,0.000000,0
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,21800723,AP,NaN,F,WHITE,25742920.0,2180,52.0,2180.0,52.0,0,0.410266,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,21520708,PA,Erect,F,WHITE,27674281.0,2152,19.0,2152.0,19.0,0,0.000000,0
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,21520708,LATERAL,Erect,F,WHITE,27674281.0,2152,19.0,2152.0,19.0,0,0.000000,0
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,21451104,AP,Erect,F,UNKNOWN,23865745.0,2145,57.0,2145.0,57.0,0,1.937847,1
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,21451102,AP,Erect,F,UNKNOWN,23865745.0,2145,57.0,2145.0,57.0,0,1.937847,1
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,21451103,AP,Recumbent,F,UNKNOWN,23865745.0,2145,57.0,2145.0,57.0,0,1.937847,1

In [139]:
keep_cols = ['dicom_id', 'hadm_id', 'cxr_view', 'cxr_orientation', 'subject_id', 'gender', 'age', 'stay_expire', 'icu_stay_los', 'icu_stay']
cxr_dataset_metadata = final_dataset_2[keep_cols]

In [146]:
cxr_dataset_metadata['age'].agg(['min', 'max'])

min     16.0
max    100.0
Name: age, dtype: float64

In [147]:
import numpy as np
bins = [0, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, np.inf]
names = ['<20', '20-25', '25-30', '30-35', '35-40', '40-45', '45-50', '50-55', '55-60', '60-65', '65-70',
         '70-75', '75-80', '80-85', '85-90', '90+']

cxr_dataset_metadata['ageR5'] = pd.cut(cxr_dataset_metadata['age'], bins, labels=names)

print(cxr_dataset_metadata.dtypes)

dicom_id             object
hadm_id             float64
cxr_view             object
cxr_orientation      object
subject_id            int64
gender               object
age                 float64
stay_expire           int64
icu_stay_los        float64
icu_stay              int64
ageR5              category
dtype: object

/tmpdata/ipykernel_674121/2776103254.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cxr_dataset_metadata['ageR5'] = pd.cut(cxr_dataset_metadata['age'], bins, labels=names)

In [148]:
import numpy as np
bins = [0, 20, 30, 40, 50, 60, 70, 80, 90, np.inf]
names = ['<20', '20-30', '30-40', '40-50', '50-60', '60-70','70-80', '80-90', '90+']

cxr_dataset_metadata['ageR10'] = pd.cut(cxr_dataset_metadata['age'], bins, labels=names)

print(cxr_dataset_metadata.dtypes)

dicom_id             object
hadm_id             float64
cxr_view             object
cxr_orientation      object
subject_id            int64
gender               object
age                 float64
stay_expire           int64
icu_stay_los        float64
icu_stay              int64
ageR5              category
ageR10             category
dtype: object

/tmpdata/ipykernel_674121/1167795373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cxr_dataset_metadata['ageR10'] = pd.cut(cxr_dataset_metadata['age'], bins, labels=names)

In [150]:
cxr_dataset_metadata['path'] = cxr_dataset_metadata['dicom_id']

path_before = '/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-cxr-jpg/2.0.0/resized/'
path_after = '.jpg'

cxr_dataset_metadata['path'] = cxr_dataset_metadata['path'].apply(lambda x: path_before+str(x)+path_after)

/tmpdata/ipykernel_674121/92907812.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cxr_dataset_metadata['path'] = cxr_dataset_metadata['dicom_id']
/tmpdata/ipykernel_674121/92907812.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cxr_dataset_metadata['path'] = cxr_dataset_metadata['path'].apply(lambda x: path_before+str(x)+path_after)

In [151]:
cxr_dataset_metadata[cxr_dataset_metadata['subject_id'] == 10001884].shape

(55, 13)

In [152]:
print(cxr_dataset_metadata['path'][:1].item())

/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-cxr-jpg/2.0.0/resized/02aa804e-bde0afdd-112c0b34-7bc16630-4e384014.jpg

In [153]:
import collections
collections.Counter(cxr_dataset_metadata['icu_stay_los'])

Counter({0.0: 297921,
         0.4102662037037037: 2,
         0.4975347222222222: 1,
         9.171817129629629: 4,
         4.981134259259259: 6,
         10.977222222222222: 10,
         7.032893518518519: 10,
         2.0238425925925925: 1,
         0.6789699074074074: 2,
         0.709212962962963: 2,
         16.06983796296296: 12,
         12.91130787037037: 9,
         2.916701388888889: 2,
         1.0394560185185184: 3,
         4.952106481481482: 7,
         2.022962962962963: 1,
         1.0505208333333331: 4,
         3.1687384259259264: 2,
         2.859664351851852: 3,
         1.2175: 3,
         9.362048611111112: 15,
         8.70269675925926: 5,
         8.367557870370371: 9,
         7.912337962962963: 3,
         0.8590046296296298: 1,
         3.338229166666667: 5,
         0.926851851851852: 1,
         3.766724537037037: 2,
         7.995011574074074: 3,
         9.019282407407408: 5,
         4.398703703703704: 5,
         2.5255092592592594: 2,
         0.8422453703703704: 1,
         0.5752546296296296: 1,
         3.845358796296296: 7,
         2.471168981481481: 2,
         2.075219907407407: 1,
         0.7518518518518519: 3,
         4.844085648148148: 6,
         1.1599537037037038: 5,
         1.2037152777777778: 2,
         3.3498032407407403: 3,
         4.909537037037038: 4,
         3.2677199074074075: 4,
         0.2616087962962962: 2,
         13.899224537037036: 16,
         2.1105324074074074: 3,
         7.702511574074074: 3,
         1.240324074074074: 1,
         3.609768518518518: 4,
         3.062326388888889: 4,
         1.313287037037037: 2,
         0.8154166666666667: 4,
         7.1284375: 5,
         5.126076388888889: 4,
         7.446423611111111: 7,
         3.1651736111111117: 3,
         4.672222222222223: 2,
         9.076828703703704: 15,
         15.68892361111111: 17,
         1.788611111111111: 3,
         0.6163657407407408: 1,
         8.084953703703704: 5,
         7.0484375: 5,
         0.6638888888888889: 1,
         1.632962962962963: 6,
         1.8923842592592592: 1,
         4.446550925925926: 5,
         6.605625: 4,
         13.214675925925926: 2,
         2.8253703703703703: 4,
         21.174837962962965: 27,
         1.1508680555555555: 3,
         0.8355902777777778: 4,
         1.387013888888889: 3,
         13.258449074074074: 8,
         1.928564814814815: 1,
         6.474791666666667: 6,
         6.327037037037036: 10,
         1.403414351851852: 3,
         0.8281828703703703: 2,
         8.784178240740742: 10,
         2.939270833333333: 4,
         2.321956018518519: 1,
         3.3496875: 2,
         0.8408564814814814: 2,
         0.8129166666666666: 2,
         8.836469907407407: 8,
         16.180787037037035: 22,
         0.4577777777777778: 1,
         2.1865625: 1,
         0.8963541666666667: 1,
         10.73679398148148: 13,
         1.8357291666666664: 1,
         2.280601851851852: 3,
         3.8053125: 6,
         4.637638888888889: 4,
         3.731944444444444: 1,
         1.080833333333333: 1,
         8.39332175925926: 11,
         3.1461921296296294: 2,
         0.8418055555555556: 1,
         0.9192824074074074: 2,
         2.614976851851852: 2,
         2.0057407407407406: 4,
         2.3066319444444443: 5,
         7.157581018518518: 7,
         4.443368055555555: 1,
         3.993784722222223: 3,
         0.9985069444444444: 1,
         3.167997685185185: 1,
         0.4562615740740741: 1,
         5.041064814814814: 4,
         19.20020833333333: 14,
         1.201284722222222: 1,
         3.1463657407407406: 4,
         0.7714814814814815: 1,
         1.1719675925925923: 1,
         1.4358680555555556: 2,
         1.826898148148148: 3,
         2.3954166666666667: 2,
         0.909386574074074: 1,
         6.130925925925926: 6,
         1.024386574074074: 2,
         16.27696759259259: 34,
         2.869479166666667: 2,
         1.131585648148148: 2,
         2.009826388888889: 1,
         3.677974537037037: 6,
         1.9088310185185184: 2,
         1.953425925925926: 4,
         1.9370949074074075: 1,
         1.014328703703704: 4,
         4.895381944444445: 1,
         2.7651041666666667: 5,
         1.643587962962963: 2,
         6.895740740740741: 8,
         11.087997685185186: 11,
         4.602592592592592: 3,
         3.042777777777778: 5,
         4.898923611111111: 3,
         1.8008796296296297: 3,
         0.7304513888888887: 1,
         0.3255902777777777: 1,
         8.769305555555555: 10,
         1.5340856481481484: 3,
         0.4425925925925926: 2,
         4.710949074074073: 8,
         20.66952546296296: 19,
         1.4305208333333332: 1,
         4.691678240740741: 5,
         0.71: 1,
         2.1112037037037035: 2,
         2.250104166666667: 2,
         2.8961342592592594: 1,
         10.160474537037038: 5,
         2.0440972222222222: 1,
         0.7770717592592593: 2,
         1.0686689814814816: 2,
         1.0339814814814814: 2,
         2.200520833333333: 3,
         2.0271064814814816: 2,
         3.9534375: 9,
         3.913726851851852: 2,
         1.031099537037037: 1,
         1.3175: 1,
         0.5268750000000001: 2,
         3.1439583333333334: 2,
         1.8847685185185183: 3,
         4.669745370370371: 4,
         3.443425925925926: 4,
         1.957962962962963: 1,
         1.8416203703703704: 4,
         1.1783564814814815: 2,
         4.754027777777778: 6,
         1.3269444444444445: 1,
         3.38875: 1,
         1.0582870370370372: 2,
         0.5929745370370371: 1,
         3.987534722222222: 7,
         3.024895833333334: 2,
         4.320983796296296: 7,
         1.5369907407407408: 5,
         2.773252314814815: 2,
         5.324375000000001: 3,
         4.155057870370371: 2,
         12.6490625: 5,
         1.0800347222222222: 3,
         2.548287037037037: 1,
         0.9795601851851852: 2,
         3.858564814814815: 1,
         5.667986111111111: 3,
         0.6167476851851852: 2,
         2.343414351851852: 5,
         0.9538657407407408: 5,
         3.148043981481482: 4,
         13.67412037037037: 15,
         2.657939814814815: 2,
         6.1823958333333335: 8,
         1.0162152777777778: 1,
         2.1482060185185183: 2,
         0.8421875: 4,
         0.6300347222222222: 1,
         1.224675925925926: 1,
         4.297199074074074: 6,
         13.453344907407406: 10,
         1.1698148148148149: 1,
         1.537025462962963: 1,
         9.454953703703705: 7,
         2.643298611111111: 1,
         0.9515856481481482: 3,
         0.988912037037037: 2,
         2.0750578703703706: 1,
         2.072372685185185: 2,
         1.033912037037037: 2,
         2.1757754629629638: 4,
         1.7596412037037037: 6,
         5.841863425925926: 7,
         1.764039351851852: 2,
         7.79425925925926: 4,
         8.848136574074074: 12,
         1.2208217592592592: 3,
         2.616435185185185: 3,
         0.7155324074074073: 1,
         3.858668981481482: 1,
         3.513680555555556: 2,
         1.7571990740740742: 3,
         9.213564814814816: 9,
         1.717013888888889: 2,
         1.4668055555555557: 1,
         2.2784722222222222: 4,
         1.9202777777777775: 3,
         1.3166087962962962: 1,
         0.9585648148148148: 2,
         2.116203703703704: 4,
         2.900659722222222: 6,
         13.026898148148147: 6,
         5.691446759259258: 1,
         1.6883912037037037: 3,
         0.5602430555555555: 3,
         0.9740972222222224: 2,
         2.659826388888889: 2,
         0.7024074074074074: 1,
         2.165625: 1,
         3.602777777777778: 1,
         8.044305555555555: 10,
         2.114282407407407: 5,
         12.81806712962963: 17,
         1.630763888888889: 5,
         4.070416666666667: 2,
         0.4040046296296296: 1,
         1.6424189814814818: 1,
         5.781770833333333: 3,
         1.823865740740741: 1,
         1.1246527777777775: 1,
         22.030879629629627: 23,
         0.6722800925925926: 2,
         5.613738425925926: 2,
         0.6627662037037038: 1,
         1.472824074074074: 2,
         0.8083912037037037: 2,
         1.0435532407407406: 2,
         5.80042824074074: 2,
         1.9044328703703703: 2,
         1.194525462962963: 1,
         3.3026273148148158: 2,
         3.8610069444444446: 1,
         3.2232175925925923: 2,
         1.3518287037037038: 1,
         1.1536921296296296: 2,
         2.3472685185185185: 2,
         2.779386574074074: 1,
         0.9624768518518518: 3,
         0.8828240740740741: 2,
         2.149699074074074: 1,
         1.3812962962962965: 3,
         5.409340277777777: 9,
         1.1389814814814816: 2,
         31.857314814814814: 20,
         1.7708680555555558: 2,
         3.157986111111111: 2,
         1.0922337962962962: 2,
         6.794861111111112: 4,
         2.3405555555555555: 4,
         50.26020833333333: 24,
         2.488391203703704: 4,
         17.827928240740743: 6,
         1.8345717592592592: 3,
         2.2387615740740743: 2,
         0.8387037037037036: 2,
         1.7911342592592592: 1,
         2.9051273148148145: 2,
         5.172476851851852: 3,
         3.2323032407407406: 7,
         0.8319328703703704: 2,
         1.0386342592592592: 3,
         0.8151157407407408: 1,
         2.626087962962963: 2,
         3.083541666666667: 1,
         1.354074074074074: 5,
         11.038761574074076: 2,
         7.226574074074073: 7,
         4.11630787037037: 8,
         3.4605092592592595: 5,
         4.2814351851851855: 1,
         1.904409722222222: 1,
         5.597766203703704: 7,
         2.2237152777777776: 4,
         0.948287037037037: 4,
         3.768206018518518: 8,
         1.7630671296296294: 1,
         1.8920023148148144: 1,
         4.984363425925927: 6,
         1.1216087962962962: 1,
         6.802152777777778: 11,
         24.7984375: 23,
         6.278680555555556: 5,
         2.089155092592593: 4,
         3.0410300925925924: 1,
         2.8878240740740737: 1,
         0.8474421296296296: 2,
         0.8148148148148148: 1,
         1.708715277777778: 1,
         0.8552546296296296: 1,
         1.0813541666666666: 4,
         5.365000000000001: 9,
         13.108449074074075: 6,
         2.3656597222222224: 2,
         2.00625: 2,
         2.7991782407407406: 1,
         6.812986111111112: 4,
         8.436319444444445: 3,
         5.1978125: 1,
         1.8951041666666664: 3,
         2.8729629629629625: 2,
         4.423564814814815: 4,
         0.9928819444444444: 2,
         0.770011574074074: 1,
         0.5593750000000001: 1,
         0.6594097222222222: 2,
         1.0869444444444445: 3,
         1.2195486111111111: 1,
         1.8748958333333328: 1,
         0.4744791666666666: 1,
         1.2976736111111111: 3,
         3.9599189814814815: 2,
         0.7082175925925926: 2,
         0.9599421296296295: 1,
         5.039618055555556: 7,
         0.911539351851852: 2,
         2.0399537037037034: 1,
         17.607685185185186: 9,
         2.6850115740740743: 2,
         1.1886805555555555: 2,
         3.2368634259259257: 2,
         4.730312499999999: 4,
         2.0598495370370373: 6,
         1.0209143518518518: 2,
         1.9153587962962968: 2,
         4.954641203703704: 5,
         3.951261574074074: 3,
         4.006134259259259: 5,
         2.270300925925926: 1,
         3.633819444444444: 8,
         1.3145601851851851: 1,
         11.21925925925926: 13,
         1.3674652777777778: 1,
         3.667511574074074: 4,
         1.1741550925925923: 3,
         0.9495949074074074: 5,
         3.1664351851851857: 6,
         6.488113425925925: 9,
         8.892280092592593: 18,
         0.641712962962963: 3,
         2.395277777777778: 2,
         2.0989236111111107: 1,
         3.918796296296296: 5,
         3.760868055555555: 3,
         1.294039351851852: 1,
         4.183993055555555: 6,
         5.05292824074074: 5,
         2.2763541666666667: 3,
         1.5760300925925923: 2,
         0.7540393518518518: 1,
         3.436481481481481: 5,
         9.262291666666668: 4,
         0.4922916666666666: 1,
         2.4265856481481483: 3,
         0.5698032407407407: 2,
         0.8878472222222222: 2,
         0.923449074074074: 1,
         1.063611111111111: 3,
         1.4116203703703702: 1,
         1.671678240740741: 2,
         1.7565277777777777: 2,
         1.512986111111111: 1,
         0.8459606481481482: 1,
         0.8713194444444445: 1,
         3.5138541666666665: 5,
         4.17412037037037: 1,
         3.5627199074074074: 10,
         1.0941319444444444: 1,
         1.6080555555555556: 4,
         4.134363425925926: 2,
         0.4950578703703703: 1,
         0.6056712962962962: 1,
         0.9065972222222222: 1,
         0.8380092592592593: 2,
         0.4888194444444444: 1,
         3.270787037037037: 4,
         1.5574537037037035: 3,
         5.015127314814815: 3,
         7.282800925925926: 1,
         4.5967013888888895: 2,
         1.7746759259259255: 2,
         3.199085648148148: 2,
         7.595902777777778: 3,
         3.274652777777778: 4,
         1.2149537037037037: 1,
         1.1897685185185185: 1,
         4.779988425925926: 2,
         2.775775462962963: 1,
         2.675590277777778: 2,
         0.8641087962962962: 5,
         1.0798148148148148: 1,
         5.066782407407408: 14,
         6.698101851851852: 6,
         2.925671296296296: 2,
         3.646157407407408: 8,
         1.2926967592592593: 4,
         6.071724537037036: 10,
         6.946435185185185: 3,
         5.144814814814815: 9,
         7.969710648148148: 5,
         1.023240740740741: 1,
         2.1147800925925924: 2,
         4.900381944444445: 3,
         0.7543287037037038: 2,
         3.353854166666667: 1,
         1.4799999999999998: 3,
         67.8706712962963: 56,
         12.044837962962964: 6,
         1.0992476851851851: 1,
         2.361759259259259: 3,
         3.464085648148149: 3,
         2.3306597222222223: 2,
         1.5917708333333334: 2,
         5.197592592592593: 5,
         7.202453703703704: 11,
         10.834710648148148: 4,
         0.5366550925925926: 1,
         4.457268518518519: 9,
         1.0881365740740745: 3,
         2.699849537037037: 2,
         3.3234953703703702: 3,
         0.6293749999999999: 2,
         3.8597916666666663: 8,
         25.1984375: 26,
         7.904259259259259: 7,
         16.83729166666667: 10,
         1.0912962962962964: 1,
         2.1218055555555555: 5,
         11.869525462962962: 11,
         0.967175925925926: 5,
         1.464386574074074: 1,
         11.317256944444445: 14,
         0.9908564814814814: 2,
         1.059837962962963: 4,
         2.2585532407407407: 3,
         22.244097222222223: 25,
         14.169560185185183: 16,
         15.16695601851852: 15,
         18.956435185185185: 28,
         2.3359027777777777: 9,
         0.4346296296296296: 2,
         1.7189351851851853: 2,
         3.147442129629629: 2,
         0.8203819444444443: 1,
         1.900601851851852: 1,
         0.0885879629629629: 1,
         1.0150347222222222: 1,
         5.217256944444444: 4,
         2.116261574074074: 3,
         1.065798611111111: 1,
         1.2872685185185186: 1,
         0.91: 1,
         0.8819097222222223: 2,
         3.640856481481481: 5,
         3.751041666666667: 3,
         3.356284722222222: 4,
         2.2501157407407404: 2,
         9.295729166666666: 2,
         2.015752314814814: 2,
         1.9933333333333332: 2,
         0.6286689814814814: 1,
         2.115231481481481: 3,
         3.2828472222222227: 1,
         2.8325578703703704: 2,
         1.1172453703703702: 1,
         1.2947453703703704: 2,
         1.0277546296296296: 4,
         1.2622916666666668: 1,
         5.717662037037036: 6,
         1.5968634259259258: 1,
         5.980856481481481: 9,
         4.218645833333333: 3,
         0.3941319444444444: 4,
         1.2791203703703704: 1,
         3.346134259259259: 4,
         6.842951388888889: 2,
         6.379143518518519: 3,
         11.00648148148148: 2,
         2.7403125: 1,
         17.186944444444446: 28,
         15.552905092592594: 18,
         12.17633101851852: 10,
         3.9265625: 2,
         1.9568402777777776: 2,
         5.784537037037037: 8,
         2.3713310185185184: 2,
         1.5393055555555557: 3,
         1.1091319444444443: 1,
         7.813113425925926: 7,
         0.5994560185185186: 1,
         5.036597222222222: 7,
         11.015162037037037: 8,
         3.390868055555556: 2,
         1.2903703703703704: 4,
         4.024606481481482: 5,
         3.984918981481482: 3,
         4.986909722222221: 9,
         1.5884722222222225: 2,
         2.6284375: 7,
         4.821006944444444: 1,
         3.818460648148148: 3,
         1.5046527777777776: 1,
         4.4291782407407405: 1,
         0.3728703703703703: 2,
         21.09752314814815: 15,
         2.3966435185185184: 3,
         33.74423611111111: 28,
         7.768321759259259: 5,
         1.255821759259259: 1,
         7.1896412037037045: 8,
         1.375300925925926: 3,
         1.0535532407407406: 1,
         1.7315393518518516: 1,
         3.560810185185185: 2,
         12.256273148148148: 16,
         2.648136574074074: 3,
         0.8880902777777777: 1,
         0.8303935185185186: 2,
         1.6979976851851852: 5,
         1.0282638888888889: 1,
         2.550590277777778: 2,
         5.249733796296296: 3,
         1.865914351851852: 4,
         6.226608796296297: 7,
         0.6244097222222222: 1,
         2.07931712962963: 3,
         1.3367708333333337: 1,
         4.877233796296296: 6,
         4.215775462962963: 2,
         0.6456597222222222: 4,
         7.699016203703704: 6,
         7.046840277777778: 10,
         1.4041435185185185: 1,
         3.85025462962963: 8,
         2.1269097222222224: 8,
         1.8711805555555556: 3,
         2.6898032407407406: 3,
         8.097858796296295: 10,
         2.513402777777778: 2,
         1.6172106481481483: 1,
         1.145324074074074: 1,
         8.567372685185186: 2,
         0.518888888888889: 4,
         1.8410185185185184: 1,
         0.561712962962963: 2,
         1.7906828703703703: 2,
         1.683587962962963: 4,
         3.1858680555555554: 8,
         0.8293402777777777: 3,
         3.283680555555556: 1,
         1.1660185185185183: 1,
         3.0438310185185187: 4,
         0.6943518518518519: 4,
         5.981724537037036: 1,
         1.3272453703703704: 1,
         4.082673611111111: 9,
         2.327199074074074: 1,
         0.5161226851851852: 1,
         0.4923726851851851: 1,
         1.9272800925925928: 4,
         1.5815046296296298: 2,
         2.662708333333333: 3,
         2.8548379629629625: 4,
         1.592650462962963: 1,
         14.52125: 18,
         15.147037037037038: 15,
         3.449849537037037: 2,
         6.705497685185185: 1,
         1.320023148148148: 3,
         0.4119907407407407: 2,
         5.037789351851852: 1,
         1.6783217592592592: 1,
         1.844201388888889: 4,
         2.071180555555556: 3,
         1.0811342592592592: 1,
         4.870173611111111: 1,
         1.3148148148148149: 1,
         5.8964583333333325: 2,
         2.133622685185185: 2,
         2.033564814814815: 1,
         4.605902777777778: 1,
         2.1634953703703705: 1,
         1.1382175925925926: 1,
         2.203819444444445: 1,
         1.4685416666666666: 2,
         1.9406597222222224: 2,
         4.142060185185185: 2,
         6.907673611111111: 7,
         2.8420717592592597: 6,
         4.739884259259259: 1,
         1.084537037037037: 4,
         1.9314930555555556: 1,
         1.7913425925925928: 2,
         12.03636574074074: 6,
         3.067349537037037: 3,
         0.5719675925925926: 1,
         2.687418981481481: 4,
         0.6011574074074074: 1,
         3.5213194444444444: 2,
         1.799837962962963: 2,
         1.2639814814814816: 2,
         1.8659837962962964: 1,
         75.09922453703703: 53,
         0.8296875: 2,
         0.1641087962962963: 2,
         2.208101851851852: 3,

In [154]:
cxr_dataset_metadata['gender'].value_counts()

M    196446
F    179775
Name: gender, dtype: int64

In [155]:
import collections
collections.Counter(cxr_dataset_metadata['cxr_view'])

Counter({'PA': 96161,
         'LATERAL': 82853,
         'AP': 147173,
         'LL': 35133,
         nan: 15769,
         'LAO': 3,
         'RAO': 3,
         'AP AXIAL': 2,
         'SWIMMERS': 1,
         'PA LLD': 4,
         'AP LLD': 2,
         'XTABLE LATERAL': 2,
         'AP RLD': 2,
         'PA RLD': 1,
         'LPO': 1})

In [156]:
cxr_dataset_metadata.to_csv('./ehr_dataset_last.csv')